export const PERMISSIONS = {
  language: {
    get_all_languages: 'get_all_languages',
    create_language: 'create_language',
    edit_language: 'edit_language',
    delete_language: 'delete_language',
  },
  translate: {
    get_all_translates: 'get_all_translates',
    get_one_translate: 'get_one_translate',
    get_single_translate_by_code: 'get_single_translate_by_code',
    search_translate_by_code: 'search_translate_by_code',
    create_translate: 'create_translate',
    edit_translate: 'edit_translate',
    delete_translate: 'delete_translate',
  },
  category: {
    get_all_categorys: 'get_all_categorys',
    get_one_category: 'get_one_category',
    create_category: 'create_category',
    edit_category: 'edit_category',
    delete_category: 'delete_category',
    search_category: 'search_category',
  },
  course: {
    get_all_courses: 'get_all_courses',
    get_one_course: 'get_one_course',
    create_course: 'create_course',
    edit_course: 'edit_course',
    delete_course: 'delete_course',
    search_course: 'search_course',
  },
  course_intend: {
    get_all_course_intends: 'get_all_course_intends',
    get_one_course_intend: 'get_one_course_intend',
    create_course_intend: 'create_course_intend',
    edit_course_intend: 'edit_course_intend',
    delete_course_intend: 'delete_course_intend',
    search_course_intend: 'search_course_intend',
  },
  lesson: {
    get_all_lessons: 'get_all_lessons',
    get_one_lesson: 'get_one_lesson',
    create_lesson: 'create_lesson',
    edit_lesson: 'edit_lesson',
    delete_lesson: 'delete_lesson',
    search_lesson: 'search_lesson',
  },
  module: {
    get_all_modules: 'get_all_modules',
    get_one_module: 'get_one_module',
    create_module: 'create_module',
    edit_module: 'edit_module',
    delete_module: 'delete_module',
  },
  user: {
    delete_user: 'delete_user',
    edit_user: 'edit_user',
    create_user: 'create_user',
    get_all_users: 'get_all_users',
    get_one_user: 'get_one_user',
  },
  model: {
    get_all_models: 'get_all_models',
    get_one_model: 'get_one_model',
    create_model: 'create_model',
    edit_model: 'edit_model',
    delete_model: 'delete_model',
  },
  permission: {
    get_all_permissions: 'get_all_permissions',
    get_one_permission: 'get_one_permission',
    create_permission: 'create_permission',
    edit_permission: 'edit_permission',
    delete_permission: 'delete_permission',
  },
  roles: {
    get_all_roles: 'get_all_roles',
    create_roles: 'create_roles',
    edit_roles: 'edit_roles',
    delete_roles: 'delete_roles',
  },
  resource: {
    get_all_resources: 'get_all_resources',
    get_one_resource: 'get_one_resource',
    create_resource: 'create_resource',
    update_resource: 'update_resource',
    delete_resource: 'delete_resource',
  },
  quiz: {
    get_all_quizes: 'get_all_quizes',
    get_one_quiz: 'get_one_quiz',
    get_quiz_by_courseId: 'get_quiz_by_courseId',
    create_quiz: 'create_quiz',
    edit_quiz: 'edit_quiz',
    delete_quiz: 'delete_quiz',
  },
  quiz_question: {
    get_all_quiz_questions: 'get_all_quiz_questions',
    get_one_quiz_question: 'get_one_quiz_question',
    get_one_quiz_question_by_quizId: 'get_one_quiz_question_by_quizId',
    create_quiz_question: 'create_quiz_question',
    edit_quiz_question: 'edit_quiz_question',
    delete_quiz_question: 'delete_quiz_question',
  },
  quiz_answer: {
    get_all_quiz_answers: 'get_all_quiz_answers',
    get_one_quiz_answer: 'get_one_quiz_answer',
    get_one_quiz_answer_by_questionId: 'get_one_quiz_answer_by_questionId',
    create_quiz_answer: 'create_quiz_answer',
    edit_quiz_answer: 'edit_quiz_answer',
    delete_quiz_answer: 'delete_quiz_answer',
  },
  enrollment: {
    get_all_enrollments: 'get_all_enrollments',
    get_one_enrollment: 'get_one_enrollment',
    get_enrollment_by_courseId: 'get_enrollment_by_courseId',
    create_enrollment: 'create_enrollment',
    edit_enrollment: 'edit_enrollment',
    delete_enrollment: 'delete_enrollment',
  },
  user_quiz_attempt: {
    get_all_user_quiz_attempts: 'get_all_user_quiz_attempts',
    get_one_user_quiz_attempt: 'get_one_user_quiz_attempt',
    get_user_quiz_attempt_by_userId: 'get_user_quiz_attempt_by_userId',
    create_user_quiz_attempt: 'create_user_quiz_attempt',
    delete_user_quiz_attempt: 'delete_user_quiz_attempt',
  },
};
